"""Add Event model and relationships

Revision ID: 30f43cf301b0
Revises: c82d6931ee24
Create Date: 2025-10-28 11:26:46.351751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f43cf301b0'
down_revision = 'c82d6931ee24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_prestige'), ['prestige'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_prestige'))

    # ### end Alembic commands ###
