"""Add related_post_id to Bet model

Revision ID: 439af0092790
Revises: 0bdfa60821db
Create Date: 2025-10-30 10:08:30.672820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439af0092790'
down_revision = '0bdfa60821db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_post_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_column('related_post_id')

    # ### end Alembic commands ###
