"""dbAggiornato

Revision ID: 5db32a08071f
Revises: 94e0edc15dbe
Create Date: 2025-10-16 15:02:58.105653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db32a08071f'
down_revision = '94e0edc15dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.drop_column('distance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
