"""Make Challenge.is_active not nullable

Revision ID: 61774016d05b
Revises: 439af0092790
Create Date: 2025-11-03 09:39:25.077678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61774016d05b'
down_revision = '439af0092790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Challenges', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Challenges', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
