"""Aggiunta tabella Commenti

Revision ID: 647d89be1a6f
Revises: 91b0557525cf
Create Date: 2025-10-15 09:53:11.896874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647d89be1a6f'
down_revision = '91b0557525cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testleo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.drop_column('testleo')

    # ### end Alembic commands ###
