"""Convertito description in Text

Revision ID: 69265d423542
Revises: 98f53aac5f87
Create Date: 2025-11-10 17:11:31.790985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69265d423542'
down_revision = '98f53aac5f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
