"""Add classic_status to Route model

Revision ID: 6d31b91d4eb6
Revises: 41fb8ea4f823
Create Date: 2025-10-24 09:03:07.068539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d31b91d4eb6'
down_revision = '41fb8ea4f823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classic_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_Routes_classic_status'), ['classic_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Routes_classic_status'))
        batch_op.drop_column('classic_status')

    # ### end Alembic commands ###
