"""Add Group models and relationships

Revision ID: 7d08fe642b8e
Revises: 6d31b91d4eb6
Create Date: 2025-10-24 09:53:28.551015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d08fe642b8e'
down_revision = '6d31b91d4eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_posts_group_id'))
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
