"""dbAggiornato

Revision ID: 81d0ae27287e
Revises: 31d6a7f3c829
Create Date: 2025-10-16 13:45:56.087455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d0ae27287e'
down_revision = '31d6a7f3c829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
