"""Add description to Route model

Revision ID: 91b0557525cf
Revises: 23e6ebea187d
Create Date: 2025-10-14 13:43:23.200586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b0557525cf'
down_revision = '23e6ebea187d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registered_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_on', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
