"""dbAggiornato

Revision ID: 94e0edc15dbe
Revises: 81d0ae27287e
Create Date: 2025-10-16 13:51:43.444890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e0edc15dbe'
down_revision = '81d0ae27287e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.alter_column('route_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.alter_column('route_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
