"""empty message

Revision ID: a3f88b0f56c8
Revises: fb085b63ec45
Create Date: 2025-10-20 12:34:43.313620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f88b0f56c8'
down_revision = 'fb085b63ec45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.drop_column('testleo')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('Routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testleo', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
