"""Add prestige and title to User model

Revision ID: c82d6931ee24
Revises: 7d08fe642b8e
Create Date: 2025-10-28 10:41:55.396461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82d6931ee24'
down_revision = '7d08fe642b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Per 'prestige', diciamo di usare 0 per tutti gli utenti esistenti
        batch_op.add_column(sa.Column('prestige', sa.Integer(), nullable=False, server_default='0'))
        
        # Per 'title', diciamo di usare 'Popolano' per tutti gli utenti esistenti
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False, server_default='Popolano'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_prestige'))
        batch_op.drop_column('title')
        batch_op.drop_column('prestige')

    # ### end Alembic commands ###
