"""dbAggiornato

Revision ID: fb085b63ec45
Revises: 5db32a08071f
Create Date: 2025-10-20 09:52:57.716595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb085b63ec45'
down_revision = '5db32a08071f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        # --- MODIFICA QUI ---
        # Aggiungi server_default='user_post' per riempire i valori esistenti
        batch_op.add_column(sa.Column('post_category', sa.String(length=50), nullable=False, server_default='user_post'))
        
        # Questa linea va bene così com'è
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))
        
        # Questa linea va bene così com'è
        batch_op.create_index(batch_op.f('ix_posts_post_category'), ['post_category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_post_category'))
        batch_op.drop_column('meta_data')
        batch_op.drop_column('post_category')

    # ### end Alembic commands ###